----
- name: docker compose deploy
  hosts: docker-server
  vars_prompt: 
    - name: docker_password
      prompt: enter password for docker
  tasks:
    - name: copy docker compose 
      copy:
       src: /usr/bin
       dest: /home/ec2-user
    - name: docker login
      docker_login:
         registry_url: https://index.docker.io/v1
         username: praveen
         password: "{{docker_password}}"
    - name: start the container from compose
      docker_compose:   
        project_src: /home/ec2-user  