pipeeline{
    agentany
    environment {
        ansible_server = "172.21.19.22"
    }
       stages{
         stage("copy files from local to ansible"){
             steps{
                 script{
                    echo "copying all the neccesary files to the ansiblee control node "
                      sshagent(['ansible-key']){
                          sh "scp -o stricthostkeychecking=no ansible/playbooks root@${ansible_server}:/root"
                          
                          withcredentials([sshuserprivatekey(credentialsid: 'ec2-server-key', keyfilevariable: 'key-file')]){
                              sh "scp ${key-file} root@${ansible_server}:/root"
                          }
                      }
                 }
             }
          
          }
          stage("execute ansible playbook"){
              steps{
                  script{
                      echo "calling ansible playbook to configure ec2 instances"
                      def remote = [:]
                      remote.name = "ansible server"
                      remote.host = ansible_server
                      remote.allowanyHosts = true

                      withcredentials([sshprivatekey(credentialsid: 'ansible-server-key', keyfilevariable: 'key-file', usernamevariable: 'user')]){
                         remote.user = user
                         remote.keyfilevariable = key-file
                         sshscript remote: remote, command: "ansible.sh"
                         sshcommand remote: remote, command: "ansible-playbook docker.yaml"
                      }
                  }
              }
          }
       }:
}